[tool.isort]

multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120
py_version = 310
group_by_package = true

skip_glob = [
  "build/*",
  "docs/*",
  "setup.py",
  "thirdparty/*",
  ".venv*/",
  "*test_*",
  "./.vscode/*",
]

[tool.ruff]
line-length = 120
exclude = [
    "docs/",
    "venv*/",
]
target-version = "py310"
