[tool.black]
line-length = 122
include = '\.pyi?$'
exclude = '''
/(
    build
  | docs
  | setup\.py
  | thirdparty
  | \.venv.*
  | .*test_.*
  | \.mypy_cache
  | \.vscode
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 122
skip_glob = [
  "build/*",
  "docs/*",
  "setup.py",
  "thirdparty/*",
  ".venv*/",
  "*test_*",
  "./.vscode/*",
]
